name: Publish to VSCode Marketplace

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build || npm run compile || true
      - name: Download VSIX Artifact
        uses: actions/download-artifact@v4
        with:
          name: nested-file-toolkit-vsix
      - name: Publish to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          ARTIFACT_DIR="nested-file-toolkit-vsix"
          VSIX_FILE=$(ls "$ARTIFACT_DIR"/*.vsix | head -n 1)
          if [ -z "$VSIX_FILE" ]; then
            echo "No VSIX file found to publish in $ARTIFACT_DIR." && exit 1
          fi
          npx vsce publish --packagePath "$VSIX_FILE" --pat "$VSCE_PAT"
